### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by alukach**

### CODE REVIEW

**Comment by alukach** [comment]
... I'm confused as to why it has me listed as the author of this PR. 😕

**Comment by oliverroick** [comment]
Not sure either... @amplifi do you know?

**Comment by alukach** [comment]
Reading over the OAuth grants, I wouldn't think it would be permitted to make PRs on my behalf:

image

I'm not really too concerned, however it does make me raise an eyebrow  👀

**Comment by amplifi** [comment]
@oliverroick @alukach The PR gets opened in the name of whomever made the last commit, then the individual commits are by the requires.io account. The requires.io account isn't an organization member so can't make branches off master in our repos. Your OAuth list above includes writing repo hooks, which would allow the app to test a push hook using the last push to the repo for that hook; if I had to guess, that's possibly the workaround for lack of organization member privileges.

**Comment by alukach** [comment]
@amplifi It's weird, the first commit I ever made to Cadasta/cadasta-test was the [Requirements.io commit](https://github.com/Cadasta/cadasta-test/pull/35).  Somehow I think I've become the Requirements.io default user. My guess is that it's opened in the name of the last person who has registered a project on requirements.io (which would be me after setting up workertoolbox tooling)

**Pull request merged**
